In [77]:
import pandas as pd
import numpy as np
from sklearn import datasets, linear_model, model_selection
from sklearn.metrics import confusion_matrix, classification_report

In [2]:
f='data/athletes_sochi.txt'
dfs = pd.read_csv(f).dropna()

In [18]:
dfs = pd.read_csv(f).dropna()
dfs["BMI"] = dfs["weight"] / (dfs["height"]**2)
alldata = dfs[ ['weight', 'height', 'age', "BMI", 'gender'] ]
alldata

      weight  height  age        BMI  gender
0       68.0    1.72   17  22.985398    Male
1       85.0    1.85   27  24.835646    Male
2       68.0    1.78   21  21.461937    Male
4       82.0    1.86   21  23.702162    Male
5       57.0    1.75   21  18.612245    Male
...      ...     ...  ...        ...     ...
2851    98.0    1.93   28  26.309431    Male
2853    60.0    1.70   31  20.761246  Female
2854    65.0    1.68   28  23.030045  Female
2856    68.0    1.76   22  21.952479    Male
2857    54.0    1.58   19  21.631149  Female

[2479 rows x 5 columns]

In [93]:
allinput = alldata[ ['weight', 'height', 'age', 'BMI'] ]
alloutput = alldata["gender"].apply(lambda x: int(x == "Male"))
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(allinput, alloutput, test_size=0.2)

model_old = linear_model.LogisticRegression()
model_old.fit(X_train[['weight', 'height', 'BMI']].values, Y_train)

model_new = linear_model.LogisticRegression()
model_new.fit(X_train.values, Y_train)

Y_test_predicted_old = model_old.predict(X_test[['weight', 'height', 'BMI']].values)
Y_test_predicted_new = model_new.predict(X_test.values)

In [95]:
[tn, fp], [fn, tp] = confusion_matrix(Y_test, Y_test_predicted_old)
confusion_matrix(Y_test, Y_test_predicted_old)
print("old Accuracy: ", (tn + tp) / (tp + fp + tn + fn))

[tn, fp], [fn, tp] = confusion_matrix(Y_test, Y_test_predicted_new)
confusion_matrix(Y_test, Y_test_predicted_new)
print("new Accuracy: ", (tn + tp) / (tp + fp + tn + fn))

old Accuracy:  0.8709677419354839
new Accuracy:  0.8729838709677419